### ISSUE TITLE
Information on Tauri is incorrect and outdated

### ISSUE THREAD

**Issue by Poopooracoocoo** [styfle/awesome-desktop-js#51]
>[Tauri](https://tauri.studio/) - Build desktop apps with a Rust backend and a system webview. For the webview, Tauri uses Cocoa/WebKit on macOS, gtk-webkit2 on Linux and MSHTML(IE10/11) or Webkit via EdgeHTML/Chakra on Windows.

Tauri does not use MSHTML or EdgeHTML on Windows. Both the [Tauri](https://github.com/tauri-apps/tauri) repo and [Wry](https://github.com/tauri-apps/wry) repo say that it uses WebView2 provided by Microsoft Edge Chromium.

Tauri's documentation used to say this: https://web.archive.org/web/20210220042625/https://tauri.studio/en/docs/getting-started/technical-details/

**Comment by styfle** [comment]
Thanks, fixed in #52 👍
